### PR TITLE
Fix current_row type mismatches

### LINKED ISSUE #1197: Lister does use undefined property "current_row"
https://github.com/atk4/ui/blob/3fd37f0bee0d43f01e9eccb41e96b9dc3466d5ca/src/Lister.php#L139

Either define it properly or do not use it at all.

### LINKED ISSUE #1209: Demos Table2.php issue
Table current_row is now an array : https://github.com/atk4/ui/blob/0652ab852a40a89f8a49a1806b51fba063854842/src/Table.php#L491

in demos/table2.php is used as a model
https://github.com/atk4/ui/blob/0652ab852a40a89f8a49a1806b51fba063854842/demos/collection/table2.php#L28

### PR DESCRIPTION
**Pull request by mvorisek**
fixes #1209
fixes #1197

### CODE REVIEW

**Comment by DarkSide666** [comment]
I think that it should be like this
```
foreach ($this->model as $junk) {
    $this->current_id = $this->model->id;
    $this->current_row = $this->model->get();
    ...
```
but need to check how bad this BC breaking change could be.

**Comment by romaninsh** [comment]
I think there is a certain sense if current_row contains return of model iterator (e.g. see https://github.com/atk4/data/pull/591#issuecomment-641104171),

if we intend to drop array-access then why use array here? Isn't that inconsistent?

File: src/Lister.php [hunk 1]
```diff
@@ -141,7 +144,8 @@ public function renderView()
 
         // Iterate data rows
         $this->_rendered_rows_count = 0;
-        foreach ($this->model as $this->current_id => $this->current_row) {
+        foreach ($this->model as $ignore) {
+            $this->current_row = $this->model;
```
Comment (DarkSide666) [inline src/Lister.php:148]: I guess you could just do `foreach ($this->model as $this->current_row)` no?

**Review by DarkSide666 — APPROVED** [review]
