### PR TITLE
Fix #719 and #720

### LINKED ISSUE #719: Bug in custom CRUD->itemCreate support
See lines here https://github.com/atk4/ui/blob/develop/src/CRUD.php#L135
That implementation is wrong.

### PR DESCRIPTION
**Pull request by DarkSide666**
Fix #719 and #720

### CODE REVIEW

**Comment by romaninsh** [comment]
PHP Notice:  Use of undefined constant menu - assumed 'menu' in /home/travis/build/atk4/ui/src/CRUD.php on line 136

File: src/CRUD.php [hunk 1]
```diff
@@ -133,6 +133,9 @@ public function initCreate()
     {
         // setting itemCreate manually is possible.
         if (!$this->itemCreate) {
+            if (!$this>menu) {
```
Comment (kyro46) [inline src/CRUD.php]: missing - before >
