### PR TITLE
Fix input form attribute as soon as possible, needed for partial render

### LINKED ISSUE #1409: CRITICAL: when not-complete form is reloaded, the controls does not have html "form" attribute set
thus they are not associated with the "owning" form then

bug introduced in https://github.com/atk4/ui/pull/1275

### PR DESCRIPTION
**Pull request by mvorisek**
fixes https://github.com/atk4/ui/issues/1409

### CODE REVIEW

File: src/Form/Control.php [hunk 1]
```diff
@@ -127,6 +127,16 @@ protected function renderView(): void
...
     }
 
+    protected function renderTemplateToHtml(string $region = null): string
+    {
+        $output = parent::renderTemplateToHtml($region);
+
+        /** @var Form|null $form */
+        $form = $this->getClosestOwner($this, Form::class);
+
+        return $form !== null ? $form->fixFormInRenderedHtml($output) : $output;
```
Comment (mvorisek) [inline src/Form/Control.php:137]: FYI: allow controls /wo Form owner

**Review by georgehristov — APPROVED** [review]

**Comment by mvorisek** [comment]
FYI: @ibelar this was the reloading issue, now fixed
