### PR TITLE
Fix form2.php demo

### LINKED ISSUE #1704: Field names missing in Model->getField, causing corrupt Exception message
In recent develop, example `demos/form/form2.php` don't work:
- First form can never be saved, as iso ~cannot be empty, nor~ cannot it be changed
- If you deactivate all validation handling in onSubmit to make it work again, still it will throw an error `Javascript Error
Syntax error, unrecognized expression: #`

The second form throws error `Atk4\Ui\Exception: Callback requested, but never reached. You may be missing some arguments in request URL.` on save.

### PR DESCRIPTION
**Pull request by ibelar**
Fix: #1704

### CODE REVIEW

**Comment by mvorisek** [comment]
@ibelar how can this fix #1704 when there is no JS related code fixed?

`Javascript Error Syntax error, unrecognized expression: #` is something that should never happen as it signals some non-100% quoting somewhere

File: demos/form/form2.php [hunk 1]
```diff
@@ -21,55 +22,61 @@
...
+$formCodes->addControl(Country::hinting()->fieldName()->iso3, ['width' => 'four'])->iconLeft = 'flag';
+$formCodes->addControl(Country::hinting()->fieldName()->numcode, ['width' => 'four'])->iconLeft = 'flag';
+$formCodes->addControl(Country::hinting()->fieldName()->phonecode, ['width' => 'four'])->iconLeft = 'flag';
 
 // form names field group
 $formNames = $form->addGroup(['More Information about you']);
-$formNames->addControl('first_name', ['width' => 'eight']);
-$formNames->addControl('middle_name', ['width' => 'three']);
-$formNames->addControl('last_name', ['width' => 'five']);
+$formNames->addControl('f_name', ['width' => 'five', 'caption' => 'First Name']);
```
Comment (mvorisek) [inline demos/form/form2.php]: original `first_name` looks much better to me

File: src/Form.php [hunk 2]
```diff
@@ -307,6 +307,9 @@ public function onSubmit(\Closure $callback)
             } catch (\Atk4\Data\ValidationException $val) {
                 $response = [];
                 foreach ($val->errors as $field => $error) {
+                    if (!$field) {
+                        throw ($val);
```
Comment (mvorisek) [inline src/Form.php]:
```suggestion
            } catch (\Atk4\Data\ValidationException $e) {
                $response = [];
                foreach ($val->errors as $field => $error) {
                    if (!$field) {
                        throw $e;
```

File: src/JsCallback.php [hunk 3]
```diff
@@ -115,12 +115,8 @@ public function set($fx = null, $args = null)
...
 
                 $this->terminateAjax($ajaxec);
-            } catch (\Atk4\Data\ValidationException $e) {
-                // Validation exceptions will be presented to user in a friendly way
-                $msg = new Message($e->getMessage());
-                $msg->addClass('error');
-
-                $this->terminateAjax(null, $msg->getHtml(), false);
+            } catch (\Exception $e) {
+                $this->terminateAjax(null, $this->getApp()->renderExceptionHtml($e), false);
```
Comment (mvorisek) [inline src/JsCallback.php]: one question - why catch, when we can leave to app exception handler?

Comment (ibelar) [reply src/JsCallback.php]: Do you mean `throw ($e)`?

Comment (ibelar) [reply src/JsCallback.php]: or remove entire try - catch block?

File: src/Form.php (hunk 2 above)
Comment (ibelar) [reply src/Form.php]: missing change for $val->errors - I will update

**Comment by ibelar** [comment]
@mvorisek - any idea why all MSSQL test are failing?

File: src/JsCallback.php (hunk 3 above)
Comment (mvorisek) [reply src/JsCallback.php]: remove entire catch, I think it is not needed as renderExceptionHtml is the normal exception render when an exception is caught in app, but of course check if the behaviour is the same...

**Comment by mvorisek** [comment]
> @mvorisek - any idea why all MSSQL test are failing?

yes, merge the latest develop (standard DBAL DSN is required in GH CI config)

**Comment by ibelar** [comment]
> yes, merge the latest develop (standard DBAL DSN is required in GH CI config)

Ah - thanks

File: src/JsCallback.php (hunk 3 above)
Comment (ibelar) [reply src/JsCallback.php]: Done!

File: src/Behat/Context.php [hunk 4]
```diff
@@ -45,7 +45,9 @@ public function waitUntilLoadingAndAnimationFinished(AfterStepScope $event): voi
     {
         $this->jqueryWait();
         $this->disableAnimations();
-        $this->assertNoException();
+        if ($event->getFeature()->getTitle() !== 'Exception') {
```
Comment (mvorisek) [inline src/Behat/Context.php]: we need to have a special step for testing exceptions, this is a dirty hack, I will fix it

File: src/Form.php [hunk 5]
```diff
@@ -304,9 +304,12 @@ public function onSubmit(\Closure $callback)
                 }
 
                 return $response;
-            } catch (\Atk4\Data\ValidationException $val) {
+            } catch (\Atk4\Data\ValidationException $e) {
                 $response = [];
-                foreach ($val->errors as $field => $error) {
+                foreach ($e->errors as $field => $error) {
+                    if (!$field) {
```
Comment (mvorisek) [inline src/Form.php]: as @mkrecek234 pointed out, this needs to be fixed in data, however, I belive, there is a usecase when field is empty when the source of the validation exception is unknown

Comment (mvorisek) [reply src/Form.php]: fixed in https://github.com/atk4/data/pull/942

File: src/JsCallback.php [hunk 6]
```diff
@@ -102,26 +102,18 @@ public function set($fx = null, $args = null)
...
-                }
-
-                $response = $fx(...array_merge([$chain], $values));
+            $values = [];
+            foreach ($this->args as $key => $value) {
+                $values[] = $_POST[$key] ?? null;
+            }
 
-                $ajaxec = $response ? $this->getAjaxec($response, $chain) : null;
+            $response = $fx(...array_merge([$chain], $values));
```
Comment (mvorisek) [inline src/JsCallback.php]:
```suggestion
            $response = $fx($chain, ...$values);
```
