### PR TITLE
[fix] Demo Tutorial intro

### LINKED ISSUE #1528: Demo Tutorial Wizard Last step "Model need to be loaded" Exception
browsing Demo page, 2.4.x, walked through the tutorial, step 0,1,2 ending in
https://ui.agiletoolkit.org/demos/tutorial/intro.php?__atk_callback=atk_layout_maestro_wizard&atk_layout_maestro_wizard=2
works ok, when clicking next, going to
https://ui.agiletoolkit.org/demos/tutorial/intro.php?__atk_callback=atk_layout_maestro_wizard&atk_layout_maestro_wizard=3
it fails with  Critical Error  tk4\ui\Exception: Model need to be loaded.

Stack Trace
  | src/Card.php:188 |   |  
6 | demos/tutorial/intro.php:191 | atk_layout_maestro_wizard_demo_demo_view_2_card | setModel(...)
5 | demos/_includes/Demo.php:54 |   | atk4\ui\demo\{closure}(...)
4 | demos/tutorial/intro.php:192 | atk_layout_maestro_wizard_demo_demo | setCodeAndCall(...)
3 | src/Callback.php:67 |   | atk4\ui\demo\{closure}(...)
2 | src/Wizard.php:114 | atk_layout_maestro_wizard_callback | set(...)
1 | demos/tutorial/intro.php:201 | atk_layout_maestro_wizard | addStep(...)

I did not have time to do any troubleshooting or testing, just figured I would flag it - probably an easy fix for the seasoned agile-ui'rs

2020-11-02 00_05_26-agile-ui-demo-tut

### PR DESCRIPTION
**Pull request by ibelar**
fix #1528

### CODE REVIEW

File: demos/tutorial/intro.php [hunk 1]
```diff
@@ -171,24 +188,27 @@ protected function init(): void
...
-        $model = new \atk4\ui\demo\DemoInvoice(new \atk4\data\Persistence\Array_($_SESSION['x'] ?? []));
+        $model = new \atk4\ui\demo\DemoInvoice(new \atk4\data\Persistence\Array_($_SESSION['x'] ?? []), ['dateFormat' => $app->ui_persistence->date_format]);
         $model->onHook(\atk4\data\Model::HOOK_AFTER_SAVE, function ($model) {
             $_SESSION['x'][$model->getId()] = $model->get();
         });
 
+        Header::addTo($owner, ['Record display in Card View using model data.']);
         $model->tryLoad(1);
-        \atk4\ui\Card::addTo($owner)->setModel($model, ['date']);
+        $model->loaded()
```
Comment (mvorisek) [inline demos/tutorial/intro.php]: use if/else, ternary should be used for passing a or b, but not for decisions, improve readability...

File: demos/_includes/DemoInvoice.php [hunk 2]
```diff
@@ -9,13 +9,23 @@
...
 
-        $this->addField('reference');
-        $this->addField('date', ['type' => 'date']);
+        $this->addField('reference', ['required' => true]);
+        $this->addField('date', [
+            'type' => 'date',
+            'required' => true,
+            'typecast' => [
+                function ($v) {
+                    return ($v instanceof \DateTime) ? date_format($v, $this->dateFormat) : $v;
```
Comment (mvorisek) [inline demos/_includes/DemoInvoice.php:26]: for what is this needed?

for UI? If so, it will affect also db typecasting, right?

File: demos/tutorial/intro.php [hunk 3]
```diff
@@ -171,24 +188,27 @@ protected function init(): void
...
             Once your model is defined, it can be re-used later with any generic view:
             EOF
     );
 
-    Demo::addTo($page)->setCodeAndCall(function (View $owner) {
+    Demo::addTo($page)->setCodeAndCall(function (View $owner) use ($app) {
         session_start();
 
-        $model = new \atk4\ui\demo\DemoInvoice(new \atk4\data\Persistence\Array_($_SESSION['x'] ?? []));
+        $model = new \atk4\ui\demo\DemoInvoice(new \atk4\data\Persistence\Array_($_SESSION['x'] ?? []), ['dateFormat' => $app->ui_persistence->date_format]);
```
Comment (mvorisek) [inline demos/tutorial/intro.php]: I think it would be more clean without `use ($app)`, ie. `$owner->getApp()->...`

File: demos/tutorial/intro.php (hunk 1 above)
Comment (ibelar) [reply demos/tutorial/intro.php]: ok

File: demos/_includes/DemoInvoice.php (hunk 2 above)
Comment (ibelar) [reply demos/_includes/DemoInvoice.php:26]: the demo use persistence array and date are not typecast without this.

File: demos/tutorial/intro.php (hunk 3 above)
Comment (ibelar) [reply demos/tutorial/intro.php]: you are right. old habit 😄

File: demos/_includes/DemoInvoice.php (hunk 2 above)
Comment (mvorisek) [reply demos/_includes/DemoInvoice.php:26]: then probably use `Y-m-d` here as this is later expected once we move to DBAL

ie. no need for `dateFormat` property at all, this will/should never handle ui typecasting

Comment (ibelar) [reply demos/_includes/DemoInvoice.php:26]: dateFormat is there only for Ui, i.e. to display input value according to ui_persistence and not for DB.

Comment (mvorisek) [reply demos/_includes/DemoInvoice.php:26]: I added this part as TODO to https://github.com/atk4/data/pull/690

here - ok for now

File: demos/tutorial/intro.php [hunk 4]
```diff
@@ -118,7 +121,7 @@
             EOF
     );
 
-    Demo::addTo($page)->setCodeAndCall(function (View $owner) {
+    Demo::addTo($page)->setCodeAndCall(function (View $owner) use ($page) {
```
Comment (mvorisek) [inline demos/tutorial/intro.php]: is seems no added use of `$page`

**Comment by mvorisek** [comment]
otherwise seems ok

File: demos/tutorial/intro.php (hunk 4 above)
Comment (ibelar) [reply demos/tutorial/intro.php]: done!

**Review by DarkSide666 — APPROVED** [review]
LGTM
