### PR TITLE
Fix filesystem import demo

### LINKED ISSUE #1827: File import demo is broken
`/demos/collection/multitable.php` and `/demos/collection/crud.php` (bottom right CRUD) demos shows zero records:

image

image

maybe this happends only when reimported, not sure, insvestigate locally, https://ui.agiletoolkit.org/demos/ is not up-too-date to check there

I have checked and there are records in the DB, but the following condition:

```
$file->addCondition($file->fieldName()->parent_folder_id, null);
```

filter out all of them...

### PR DESCRIPTION
**Pull request by mvorisek**
fixes https://github.com/atk4/ui/issues/1827

when custom path was input:

image

it was skipped for import, as it did not match the filtered items

### CODE REVIEW

File: demos/_demo-data/create-db.php [hunk 1]
```diff
@@ -350,371 +350,722 @@ public function import(array $rowsMulti)
...
-    ['id' => 358, 'name' => 'PaginatorTest.php', 'type' => 'php', 'is_folder' => false, 'parent_folder_id' => 341],
-    ['id' => 359, 'name' => 'PostTest.php', 'type' => 'php', 'is_folder' => false, 'parent_folder_id' => 341],
-    ['id' => 360, 'name' => 'RenderTreeTest.php', 'type' => 'php', 'is_folder' => false, 'parent_folder_id' => 341],
-    ['id' => 361, 'name' => 'TableColumnColorRatingTest.php', 'type' => 'php', 'is_folder' => false, 'parent_folder_id' => 341],
-    ['id' => 362, 'name' => 'TableColumnLinkTest.php', 'type' => 'php', 'is_folder' => false, 'parent_folder_id' => 341],
-    ['id' => 363, 'name' => 'TableTest.php', 'type' => 'php', 'is_folder' => false, 'parent_folder_id' => 341],
-    ['id' => 364, 'name' => 'TagTest.php', 'type' => 'php', 'is_folder' => false, 'parent_folder_id' => 341],
-    ['id' => 365, 'name' => 'ViewTest.php', 'type' => 'php', 'is_folder' => false, 'parent_folder_id' => 341],
+$model->import([
+    ['id' => 1, 'name' => '.gitattributes', 'type' => 'gitattributes', 'is_folder' => false, 'parent_folder_id' => null],
```
Comment (mvorisek) [inline demos/_demo-data/create-db.php:354]: created by:

```
$m = new Model($db, ['table' => new File($db)]);
$m->getField('id')->actual = $m->table->fieldName()->id;
$m->addField('name', ['type' => 'string', 'actual' => $m->table->fieldName()->name]);
$m->addField('type', ['type' => 'string', 'actual' => $m->table->fieldName()->type]);
$m->addField('is_folder', ['type' => 'boolean', 'actual' => $m->table->fieldName()->is_folder]);
$m->addField('parent_folder_id', ['type' => 'integer', 'actual' => $m->table->fieldName()->parent_folder_id]);
$m->setOrder('id');

$res = $m->export();
$aiOffset = reset($res)['id'] - 1;
foreach ($res as $k => $v) {
    $res[$k]['id'] = $v['id'] - $aiOffset;
    if ($v['parent_folder_id']) {
        $res[$k]['parent_folder_id'] = $v['parent_folder_id'] - $aiOffset;
    }
}

var_export($res);
```
