### PR TITLE
Fix Lookup add new button

### LINKED ISSUE #1731: Lookup "plus" feature throws error
This line causes an error when you choose to have the Lookup with Lookup::plus = true:

https://github.com/atk4/ui/blob/3cb026a3649efc1841d5d73a7608145da6212971/src/Form/Control/Lookup.php#L257

Error is "Atk4\Data\Exception: Expected model, but instance is an entity".

### PR DESCRIPTION
**Pull request by mkrecek234**
fixes https://github.com/atk4/ui/issues/1731

### CODE REVIEW

File: src/Form/Control/Lookup.php [hunk 1]
```diff
@@ -251,10 +251,10 @@ protected function initQuickNewRecord()
 
         $vp->set(function ($page) {
             $form = \Atk4\Ui\Form::addTo($page);
-
-            $entity = $this->model->createEntity();
-
-            $form->setModel($entity->setOnlyFields($this->plus['fields'] ?? []));
+
```
Comment (mvorisek) [inline src/Form/Control/Lookup.php]: trailing spaces need to be removed, see CS fixer diff

Comment (mkrecek234) [reply src/Form/Control/Lookup.php]: @mvorisek See new commit

**Comment by mvorisek** [comment]
looks good, thank you!
