### PR TITLE
[fix] Multitable demo

### LINKED ISSUE #1516: Demo bug - entity ID reassign
step to reproduce:

1. open `/demos/collection/multitable.php`
2. click any item in the table
3. you will see:
image

### PR DESCRIPTION
**Pull request by ibelar**
fix #1516

### CODE REVIEW

File: demos/collection/multitable.php [hunk 1]
```diff
@@ -38,23 +38,24 @@ public function setModel(\atk4\data\Model $model, $route = [])
 
         while ($selections && $id = array_shift($selections)) {
             $path[] = $id;
-            $model->tryLoad($id);
-            if (!$model->loaded()) {
+            $pushModel = $model->newInstance();
```
Comment (mvorisek) [inline demos/collection/multitable.php]:
```suggestion
            $pushModel = clone $model;
```

otherwise we will loose scope if set (or other settings not set in `Model::init()`)

@georgehristov should we remove `newInstance()` from Model or change it, so clone is returned instead?

**Review by mvorisek — APPROVED** [review]

File: demos/collection/multitable.php (hunk 1 above)
Comment (georgehristov) [reply demos/collection/multitable.php]: clone $model != $model->newInstance

Using newInstance is not supposed to take over the scope but only use the same connection.

Comment (mvorisek) [reply demos/collection/multitable.php]: ok - it is not clone, as it does not clone ID etc.

so `$obj->newInstance()` is strictly equivalent to `new get_class($obj)()` (only theoretical, new expr is not supported)?

if model is dynamic like now, ie. defined with scopes, what is the advantage of this function?

Comment (georgehristov) [reply demos/collection/multitable.php]: As I mentioned - also the same connection is used. Actual code speaks for itself:

```
public function newInstance(string $class = null, array $options = [])
    {
        $model = (self::class)::fromSeed([$class ?? static::class], $options);

        if ($this->persistence) {
            return $this->persistence->add($model);
        }

        return $model;
    }
```

Comment (ibelar) [reply demos/collection/multitable.php]: @mvorisek - clone $model is not fully working here too. It prevents from going deeper if a folder is click in right column. You should be able to click on the rightmost columns until you see no records. Was working using $model->newInstance()

Comment (ibelar) [reply demos/collection/multitable.php]: this is how it should look
Screen Shot 2020-10-29 at 12 11 32 PM

Comment (mvorisek) [reply demos/collection/multitable.php]: @ibelar I tested yesterday, I almost wanted to submit an issue... But it works! Ok - see https://github.com/atk4/ui/pull/1523 , we simply revert my change.
