### PR TITLE
Feature/various fixes

### LINKED ISSUE #363: CRUD does not work when placed inside Dynamic Tab
Some trouble with callbacks prevent it from working:

``` php
$t = $app->add('Tabs');
$t->addTab('first')->add(['Message', 'Go to next tab and click add']);

$t->addTab('second', function($p) {
    $p->add('CRUD')->setModel(new Client($p->app->db));
});
```

When modal opens, it displays same CRUD inside:

screen shot 2018-02-08 at 00 50 04

I think the problem is if there are multiple "cut" arguments, the top-most takes precedence, even though the bottom-one should do.

### PR DESCRIPTION
**Pull request by romaninsh**
A lot changes and fixes, mainly was required for https://github.com/atk4/mastercrud

 - Implemented BreadCrumb view with documentation and demo
 - refactored CRUD, now much more consistent, more demos comments
 - Added documentation to CRUD, after refactoring some undocumented properties
 - Console::set() second argument can override trigger event
 - Input::addAction() also adds action class (looks nicer)
 - Grid Quicksearch is now sticky
 - injecting 'quickSearch' into Grid will initialize quickSearch after you set model
 - Table::getColumnDecorators for easier access to $table->column
 - Status column now respects class
 - VirtualPages can now be nested properly: Fix #363 
 - refactored jsNotfy

### CODE REVIEW

File: src/Console.php [hunk 1]
```diff
@@ -59,7 +59,7 @@ class Console extends View implements \Psr\Log\LoggerInterface
      *
      * While inside a callback you may execute runCommand or setModel multiple times.
      */
-    public function set($callback = null, $junk = null)
+    public function set($callback = null, $event = true)
```
Comment (DarkSide666) [inline src/Console.php]: Please add description of arguments with @param

File: src/Table.php [hunk 2]
```diff
@@ -204,6 +204,16 @@ public function addDecorator($name, $decorator)
         $this->columns[$name][] = $decorator;
     }
 
+    public function getColumnDecorators($name)
```
Comment (DarkSide666) [inline src/Table.php]: Please add this method in documentation and add comments and @param

File: docs/components.rst [hunk 3]
```diff
@@ -41,11 +41,11 @@ control over even the small elements.
     text
     loremipsum
     header
+    beadcrumb
     icon
     image
     message
     tabs
-    wizard
```
Comment (romaninsh) [inline docs/components.rst]: duplicate..

File: docs/table.rst [hunk 4]
```diff
@@ -394,11 +411,11 @@ to make a note on how template caching works then,
  - values are encapsulated for named fields.
  - values are concatinated by anonymous fields.
  - <td> properties are stacked
- - last formatter will convert array with td properties into an actual tag.
+ - last decorator will convert array with td properties into an actual tag.
 
 Header and Footer
 -----------------
-When using with multiple formatters, the last formatter gets to render Header column.
+When using with multiple decorators, the last decorator gets to render Header column.
```
Comment (DarkSide666) [inline docs/table.rst]: Really last decorator is responsible of header cell? I thought first decorator do that and last decorator maybe formats footer cell ... Please check this - sounds strange.

File: src/CRUD.php [hunk 5]
```diff
@@ -12,12 +12,12 @@ class CRUD extends Grid
     public $formDefault = null;
     public $fieldsDefault = null;
 
-    public $fieldsGrid = null;
+    public $fieldsRead = null;
```
Comment (DarkSide666) [inline src/CRUD.php]: Please add appropriate @var comments for all these properties.

File: src/CRUD.php [hunk 6]
```diff
@@ -12,12 +12,12 @@ class CRUD extends Grid
...
 
-    public $columnEdit = null;
-    public $fieldsEdit = null;
-    public $formEdit = null;
-    public $pageEdit = null;
+    public $columnUpdate = null;
+    public $fieldsUpdate = null;
+    public $formUpdate = null;
```
Comment (DarkSide666) [inline src/CRUD.php]: I think to make code below simpler all defaults can be set here like this:
```
/** @var mixed Form to use when updating record */
public $formUpdate = ['Form', 'layout' => 'FormLayout/Columns'];

/** @var mixed Page to use when updating record */
public $pageUpdate = 'VirtualPage';
// or
public $pageUpdate = ['VirtualPage', 'short_name'=>'edit']; // not sure if short_name should be here or it should be unchangeable and hard-coded somewhere below in code

and so on ...
```

This way it still will be extendable/overwritable, but all such hard-coded "configuration" will be in the beginning of class code so it's easier to understand what's going on here and what property i have to overwrite to get my desired result.

File: src/Grid.php [hunk 7]
```diff
@@ -131,8 +131,7 @@ public function addQuickSearch($fields = [])
         $this->quickSearch = $form->add(new \atk4\ui\FormField\Input(['placeholder' => 'Search', 'short_name' => $this->name.'_q', 'icon' => 'search']))
             ->addClass('transparent');
 
-        if (isset($_GET[$this->name.'_q'])) {
-            $q = $_GET[$this->name.'_q'];
+        if ($q = $this->stickyGet($this->name.'_q')) {
```
Comment (DarkSide666) [inline src/Grid.php]: probably better use `$this->quickSearch->short_name` here as parameter.

File: src/Grid.php [hunk 8]
```diff
@@ -196,6 +195,10 @@ public function setModel(\atk4\data\Model $model, $columns = null)
             $this->applySort();
         }
 
+        if ($this->quickSearch && is_array($this->quickSearch)) {
```
Comment (DarkSide666) [inline src/Grid.php]: so you can define fields for quicksearch as parameter while creating Grid and then when you setModel, then it will be converted to actual QuickSearch object? Well .... yeah, why not. :)

File: src/CRUD.php (hunk 6 above)
Comment (romaninsh) [reply src/CRUD.php]: Agreed.

File: src/Grid.php (hunk 8 above)
Comment (romaninsh) [reply src/Grid.php]: yes, although it won't work with JsSearch in #368.

File: demos/notify2.php [hunk 9]
```diff
@@ -57,6 +57,8 @@ public function init()
              ->setTransition($f->model['transition'])
              ->setIcon($f->model['icon']);
 
+    var_dump($notifier->options);
```
Comment (DarkSide666) [inline demos/notify2.php]: var_dump is left here !

File: src/CRUD.php [hunk 10]
```diff
@@ -84,52 +103,129 @@ public function setModel(\atk4\data\Model $m, $defaultFields = null)
...
+            if (!is_object($this->formCreate) || !$this->formCreate->_initialized) {
+                $this->formCreate = $this->pageCreate->add($this->formCreate ?: $this->formDefault);
+            }
+
+           // $form = $page->add($this->formCreate ?: ['Form', 'layout' => 'FormLayout/Columns']);
+            $this->formCreate->setModel($this->model, $this->fieldsCreate ?: $this->fieldsDefault);
+
+            // set save handler with reload trigger
+            $this->formCreate->onSubmit(function ($form) {
+                $this->formCreate->model->save();
```
Comment (DarkSide666) [inline src/CRUD.php]: shouldn't use `$form` here instead of `$this->formCreate` ?

File: src/CRUD.php [hunk 11]
```diff
@@ -84,52 +103,129 @@ public function setModel(\atk4\data\Model $m, $defaultFields = null)
...
+            $this->model->load($this->app->stickyGet($this->name));
+
+            // Maybe developer has already created form
+            if (!is_object($this->formUpdate) || $this->formUpdate->_initialied) {
+                $this->formUpdate = $this->pageUpdate->add($this->formUpdate ?: $this->formDefault);
+            }
+
+            $this->formUpdate->setModel($this->model, $this->fieldsUpdate ?: $this->fieldsDefault );
+            $this->formUpdate->onSubmit(function ($form) {
+                $this->formUpdate->model->save();
```
Comment (DarkSide666) [inline src/CRUD.php]: shouldn't use `$form` here instead of `$this->formUpdate` ?

File: src/jsNotify.php [hunk 12]
```diff
@@ -45,8 +33,9 @@ public function setOptions($options)
      *
      * @return $this
      */
-    public function setOption($option, $value)
+    public function setMissingProperty($option, $value)
     {
+        echo 'here';exit;
```
Comment (DarkSide666) [inline src/jsNotify.php]: what's this ?

**Comment by romaninsh** [comment]
I have no clue why TravisCI is failing and not able to find "numcode" field. It works fine on local (mac). Can someone help?

File: docs/crud.rst [hunk 13]
```diff
@@ -0,0 +1,156 @@
...
+        }
+    }
+
+    $crud=$this->add([
+        'CRUD',
+        'formDefault'=>new UserForm();
+    ])->setModel($big_model);
+
+
+.. todo:: add example / test implementation
```
[the remark this answers is not in the document]
Comment (romaninsh) [reply docs/crud.rst]: now on crud page.

File: docs/crud.rst [hunk 14]
```diff
@@ -0,0 +1,156 @@
...
+    $crud=$this->add([
+        'CRUD',
+        'pageDefault'=>new TwoPanels();
+    ])->setModel(new Client($app->db));
+
+
+Notification
+============
+
+.. php:attr:: notify
```
[the remark this answers is not in the document]
Comment (romaninsh) [reply docs/crud.rst]: done.

File: src/CRUD.php (hunk 10 above)
Comment (romaninsh) [reply src/CRUD.php]: Technically it's the same, but ill change.

**Comment by DarkSide666** [comment]
Fixed few bugs and that bug with `numcode` too.
Phpunit tests now run successfully, but only feature tests fail in PHP 7.1 (https://travis-ci.org/atk4/ui/builds/348432245)
