### PR TITLE
Fix demo

### LINKED ISSUE #987: /demos/table.php - Exception Value should be scalar
Related code:
https://github.com/atk4/ui/blob/ad62e4488da24996016c6f12678d22d9799453b6/demos/table.php#L40

But `\DateTime` value should be supported.

### PR DESCRIPTION
**Pull request by DarkSide666**
1. set Faker as requirement because of demo.
2. fix demo page

fix #987

### CODE REVIEW

**Review by ibelar — APPROVED** [review]

File: demos/table.php [hunk 1]
```diff
@@ -26,9 +26,15 @@
 $table->addColumn('logo_url', [new \atk4\ui\TableColumn\Image()], ['caption'=>'Our Logo']);
 
 $table->onHook('getHTMLTags', function ($table, $row) {
-    if ($row->id == 1) {
+    switch ($row->id) {
```
Comment (mvorisek) [inline demos/table.php:29]: `$color = [1 => 'yellow', 2 => 'grey', 3 => 'brown'][$row->id] ?? ''` would be much simpler

File: demos/table.php [hunk 2]
```diff
@@ -37,10 +43,10 @@
 
 // ========================================================
 $my_array = [
-    ['name' => 'Vinny', 'surname' => 'Sihra', 'birthdate' => new \DateTime('1973-02-03')],
-    ['name' => 'Zoe', 'surname' => 'Shatwell', 'birthdate' => new \DateTime('1958-08-21')],
-    ['name' => 'Darcy', 'surname' => 'Wild', 'birthdate' => new \DateTime('1968-11-01')],
-    ['name' => 'Brett', 'surname' => 'Bird', 'birthdate' => new \DateTime('1988-12-20')],
+    ['name' => 'Vinny', 'surname' => 'Sihra', 'birthdate' => '1973-02-03'],
```
Comment (mvorisek) [inline demos/table.php:46]: From long-term view not a solution to #987 :)

File: demos/table.php (hunk 1 above)
Comment (DarkSide666) [reply demos/table.php:29]: well, yes it would :)
