### PR TITLE
Fix Grid IPP selector

### LINKED ISSUE #2016: Grid IPP change is broken
Check https://dev.agiletoolkit.org/demos/collection/grid.php and try to change the Items per Page to 25.

Error:
`Atk4\Ui\Exception: Not sure what to do with argument`

### PR DESCRIPTION
**Pull request by mkrecek234**
fix #2016

### CODE REVIEW

**Comment by mvorisek** [comment]
needs a Behat test and explanation why set should be done using string, also do not forget, IPP must be definitely typecasted with UI persistence :)

**Comment by mkrecek234** [comment]
@mvorisek Even if you raised now the bar to enforce behat tests, I cannot provide this, as it drives efforts to fix newly introduced bugs significantly, even though the fix is simply like in this case. This bug is really annoying, as it destroys the IPP functionality simply. So I would welcome either a merge by you, or any contribution by you to make it ready-to-merge also based on your lifted requirements.

**Comment by mvorisek** [comment]
Michael, adding a Behat test is not so complicated, but it is needed to prevent such bug from happening again.

Also please understand the fix is not correct as explained in my post above.

File: src/ItemsPerPageSelector.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ public function onPageLengthSelect(\Closure $fx): void
         $this->cb->set(function () use ($fx) {
             $ipp = isset($_GET['ipp']) ? (int) $_GET['ipp'] : null;
             // $this->pageLength->set(preg_replace("/\[ipp\]/", $ipp, $this->label));
-            $this->set($ipp);
+            $this->set((string) $ipp);
             $reload = $fx($ipp);
```
Comment (mvorisek) [inline src/ItemsPerPageSelector.php:64]: In `init` method a few lines above there is the same cast. The `set` is there for setting `View::$content` prop probably, the best way would be probably to remove every `set` call in order to set it for the render in `renderView`.

This and whole menu items must be typecasted using UI persistence in order for format numbers > 1k / page.

**Comment by mvorisek** [comment]
Thank you @mkrecek234, no one can break it now :)
