### PR TITLE
Fix nested modal support

### LINKED ISSUE #1699: Modal is rendered empty on the first open
Discovered on atk4/login, I think it is atk4/ui issue.

Steps to reproduce:

1. checkout https://github.com/atk4/login/pull/77
2. composer install
3. setup demo database using `atk4/login/demos/admin-setup.php`
4. open `atk4/login/demos/admin-roles.php`
5. click:
  image
6. click:
  image
7. empty modal is shown:
  image

Notes:
a) after the steps above, when you click "x" to close the modal step, it returns to the previous modal, repeating the step 6 then opens the modal correctly
b) issue is repeatable, but only once per unknown reset conditions - I use Firefox, repeatable when browser is clearly started and step 6 is clicked the first time per row record

I think there is some race condition when initializing the model step in JS. I have verified, the data are rendered from the server correctly, but not shown.

### LINKED ISSUE #1732: Cruds in multiple-layered modals behave strange
- Have a master Crud, and add Modal to open a child model crud. (1)
- You open the Child Model Crud in a Modal -there you add entries
- Works fine.
- Then select another master crud's entry (2) where you open the respective child Crud in the modal
- If you then click add, you see the previous, already filled-in form (1's child entry)
- If you close the modal manually, you see an empty (correct) add form - if you enter new entries there, it won't close the modal, but it still saves its content. If you manually close it you see the correct Crud entry.

Seems a logic error on cascaded cruds/modals.
See video here:

https://user-images.githubusercontent.com/28671486/152869240-ac988f31-39b6-41be-9642-6ab6740828c9.mov

### PR DESCRIPTION
**Pull request by mvorisek**
fixes #1732
fixes #1699
and highly improves the Behat testing quality

Steps to reproduce:

1. open debug example `demos/_unit-test/crud_gh1732.php`
2. click "flag" icon on the 1st row
3. click "edit" icon in the opened modal and notice `Mustard` name
4. click outside the modal to close it (the Product modal)
5. click outside the modal to close it (the Category modal)
7. repeat 2. step with 2nd row
8. repeat 3. step, notice, there is still `Mustard` name instead of `Cola`

### CODE REVIEW

File: src/Table/Column/ActionButtons.php [hunk 1]
```diff
@@ -90,7 +91,7 @@ public function addModal($button, $defaults, \Closure $callback, $owner = null,
 
         $modal->observeChanges(); // adds scrollbar if needed
 
-        $modal->set(function (\Atk4\Ui\Modal $t) use ($callback) {
+        $modal->set(function (View $t) use ($callback) {
```
Comment (mvorisek) [inline src/Table/Column/ActionButtons.php:94]: was bug

**Comment by mvorisek** [comment]
Request by JS seems to be correct & they are stateless, it does no matter if they are made after fresh reload or if some (other) rows were open for edit first:

```
# click 1st row
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&__atk_cbtarget=atk_layout_maestro_crud_modal_view_callbacklater&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=1&__atk_json=1
# click 1st row in inner Crud
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=1&__atk_cb__179fe490f148346474248e8e839df334__lexecutor_loader_callback=callback&__atk_cbtarget=_179fe490f148346474248e8e839df334__lexecutor_loader_callback&_24cd1c298afe084d643659706b2868b0___useraction_modalexecutor=1&step=fields

# click 2st row
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&__atk_cbtarget=atk_layout_maestro_crud_modal_view_callbacklater&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=2&__atk_json=1
# click 1st row in inner Crud
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=2&__atk_cb__179fe490f148346474248e8e839df334__lexecutor_loader_callback=callback&__atk_cbtarget=_179fe490f148346474248e8e839df334__lexecutor_loader_callback&_24cd1c298afe084d643659706b2868b0___useraction_modalexecutor=3&step=fields

# click 1st row again
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&__atk_cbtarget=atk_layout_maestro_crud_modal_view_callbacklater&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=1&__atk_json=1
# click 1st row in inner Crud
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=1&__atk_cb__179fe490f148346474248e8e839df334__lexecutor_loader_callback=callback&__atk_cbtarget=_179fe490f148346474248e8e839df334__lexecutor_loader_callback&_24cd1c298afe084d643659706b2868b0___useraction_modalexecutor=1&step=fields

# force webpage reload

# click 2st row
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&__atk_cbtarget=atk_layout_maestro_crud_modal_view_callbacklater&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=2&__atk_json=1
# click 1st row in inner Crud
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=2&__atk_cb__179fe490f148346474248e8e839df334__lexecutor_loader_callback=callback&__atk_cbtarget=_179fe490f148346474248e8e839df334__lexecutor_loader_callback&_24cd1c298afe084d643659706b2868b0___useraction_modalexecutor=3&step=fields
```

**Comment by mvorisek** [comment]
Also, when repeating 2. step and 5. step (in my env, consistency after 3rd attemp), 3 AJAX requests to load the inner Modal CRUD are sent instead of 1:

image

all same URL:

```
http://localhost/dequ_ui_vendor/atk4/ui/demos/_unit-test/crud_gh1732.php?__atk_m=atk_layout_maestro_crud_modal&__atk_cb_atk_layout_maestro_crud_modal_view_callbacklater=ajax&__atk_cbtarget=atk_layout_maestro_crud_modal_view_callbacklater&_25493768721f982fd10964dbbf12ee05__able_column_actionbuttons=1&__atk_json=1
```

this is another issue, and major one, as calling action might have side effects
